### ISSUE TITLE
Incorrect function called in localgov_subsites_paragraphs.module

### ISSUE THREAD

**Issue by AWearring** [localgovdrupal/localgov_paragraphs#120]
In [modules/localgov_subsites_paragraphs/localgov_subsites_paragraphs.module](https://github.com/localgovdrupal/localgov_paragraphs/blob/2.x/modules/localgov_subsites_paragraphs/localgov_subsites_paragraphs.module) line 122 the wrong function is called

`$variables['heading'] = _localgov_paragraphs_views_create_heading($heading_text, $heading_level);`
Should be 
`$variables['heading'] = _localgov_subsites_paragraphs_create_heading($heading_text, $heading_level);`

**Comment by AWearring** [comment]
This was introduced in https://github.com/localgovdrupal/localgov_paragraphs/pull/117

**Comment by finnlewis** [comment]
Thanks @AWearring  - looking now

**Comment by AWearring** [comment]
I've submitted a PR for it: https://github.com/localgovdrupal/localgov_paragraphs/pull/121

**Comment by ekes** [comment]
In release https://github.com/localgovdrupal/localgov_paragraphs/releases/tag/2.2.7
