### ISSUE TITLE
Switch map in contact component from Google to Open Street Map

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_paragraphs#177]
Councils are reporting issues with Google Maps in the contact component. Anecdotally some have made a switch to OSM themselves.

We're using OSM elsewhere so this is possibly the last LGD use of Google Maps.

We ought to switch this over so no future councils have to do this unnecessary work.

**Comment by finnlewis** [comment]
Also see https://github.com/localgovdrupal/localgov_paragraphs/issues/10
