### ISSUE TITLE
entity_usage does not install cleanly in Drupal 9.4.x

### ISSUE THREAD

**Issue by gregharvey** [localgovdrupal/localgov_paragraphs#54]
Hi all,

See related drupal.org issue:
* https://www.drupal.org/project/entity_usage/issues/3291423

Appreciate this isn't a LGD issue, however it does stop it installing for now - @galooph has created a patch for it here:
* https://git.drupalcode.org/project/entity_usage/-/merge_requests/22.diff

You might consider including that patch for now until it gets accepted. :-)

Thanks,

Greg

**Comment by keelanfh** [comment]
Closing as this was merged into `entity_usage`.
