### ISSUE TITLE
Move paragraphs into localgov_paragraphs

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_paragraphs#58]

**Comment by msayoung** [comment]
Notes from the conversation in tech group here: https://docs.google.com/document/d/1vCKK5djP-iZHFkZC-CYQXvVA8fLDGdTs0JGIvtmxB00/edit#heading=h.g7zyq224omr2

**Comment by msayoung** [comment]
I made a start on this branch: https://github.com/localgovdrupal/localgov_paragraphs/tree/feature/2.x/91-move-paragraphs

`feature/2.x/91-move-paragraphs`

There are submodules:

- localgov_paragraphs_banners
- localgov_paragraphs_complex
- localgov_paragraphs_contact
- localgov_paragraphs_structure

All the submodules install on a fresh install with localgov_paragraphs

Still plenty to do I'm afraid

**Comment by stephen-cox** [comment]
@msayoung I'm not seeing any changes in that branch.

The first step is to move the subsites paragraphs module into this one without making any changes to names. When we start changing names and paths of stuff we'll need to be careful we don't break existing sites. This will likely involve update hooks to change config and install / uninstall modules.

I'll start by creating a couple of PRs to move the subsites paragraphs.
