### ISSUE TITLE
Paragraph Component labels and descriptions

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_paragraphs#60]
![Image](https://user-images.githubusercontent.com/3852805/172635009-74350079-fe49-46a9-b2c7-e2d92bdee478.png)

Rename 

- Teaser block. Multiple promo blocks.
- Call out box. Promo block with background colour and optional background image.
- Custom menu block. Custom links blocks for section menus or other custom menus.
- Media with text. Image or video promo block with layout options.
- Accordion. Expandable text section.
- Link. Promoted button-style link

Write and add descriptions of each component

**Comment by msayoung** [comment]
![Image](https://user-images.githubusercontent.com/3852805/174277589-7c4a20d4-02ac-4610-87d4-e0b3d44c5f09.png)

@richard-s-rowley could you find / make icons. They display in menu when we select

**Comment by msayoung** [comment]
@stephen-cox -how difficult would it be to get the paragraph description to display alongside the name/icon in the "choose a component" screen ?



![Image](https://user-images.githubusercontent.com/3852805/174302923-3e8f36d7-1743-4773-8d06-0bd518e54d80.png)

**Comment by stephen-cox** [comment]
Not sure - would have to spend time delving into it check. It _should_ be possible with a hook_form_alter, but would need to do some digging to confirm this.

**Comment by richard-s-rowley** [comment]
[LGD microsites UI paragraph layout icons.zip](https://github.com/localgovdrupal/localgov_microsites/files/9008895/LGD.microsites.UI.paragraph.layout.icons.zip)

@maria please find icons attached for the paragraph UI

**Comment by richard-s-rowley** [comment]
![Call out box-32px](https://user-images.githubusercontent.com/51441518/176421014-ce534f47-3160-4aa2-8e07-68341d80e8aa.svg)
@msayoung how about this one? 32px is almost too small to be useful to most users. Any chance we can nudge it up even a little?

**Comment by msayoung** [comment]
that's defo better

**Comment by richard-s-rowley** [comment]
[LGD microsites UI paragraph layout icons 2.zip](https://github.com/localgovdrupal/localgov_microsites/files/9038971/LGD.microsites.UI.paragraph.layout.icons.2.zip)

Hi Maria,
New UI icons attached!
