### ISSUE TITLE
Add a listing widget paragraph

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_paragraphs#68]
A listing of things.... news / events ? Views reference with a paragraph? This should be in LocalGov paragraphs

A microsite editor 
- should be able to decide which type of things 
- how many to display 

Available views
- upcoming events - end date in the future, ascending order of start date (soonest first)
- archived events - end date in the past, descending start date (most recent first)
- News - descending post date order

- [x] Add a new listing paragraph
- [x] Add a default microsite view block to localgov_microsites_group
- [x] New release of localgov_paragraphs
- [x] Add localgov_paragraphs_views module to install profile .info.yml file (https://github.com/localgovdrupal/localgov_microsites/pull/230)
- [x] Add the paragraph to those available to the events https://github.com/localgovdrupal/localgov_microsites_group/pull/197
- [x] Add the paragraph to those available to the news https://github.com/localgovdrupal/localgov_microsites_group/pull/197
- [x] Add a new microsite view for recent news in localgov_microsites_news https://github.com/localgovdrupal/localgov_microsites_group/pull/197
- [x] Add a new microsite view for recent events in localgov_mictosites_events https://github.com/localgovdrupal/localgov_microsites_group/pull/197
- [x] Update the paragraph confiuration to limit to these three views (or displays) https://github.com/localgovdrupal/localgov_paragraphs/pull/76
- [x] Add the paragraph to those available to the promo page content type https://github.com/localgovdrupal/localgov_directories/pull/222
- [x] Add the paragraph to those available to the page content type https://github.com/localgovdrupal/localgov_page/pull/26

**Comment by finnlewis** [comment]
Questions: 

 - if we enable the paragraph first, then enable news, blogs, events, how do we inject the options into the views reference field?

**Comment by msayoung** [comment]
@markconroy @finnlewis @stephen-cox 

I've done a little experimentation. 

We have a **localgov_block_view** paragraph type that has a views reference field. 

We may want to extend it (or create another one) in the following ways
- Add the configuration option to limit the number of posts
- Update the widget to show only available views
- Add a Heading and Heading level field? (this raises another question about heading levels but leaving that for now)
- Change the label from _Block view_ to something more understandable (ideas?)

Update the field.field.node.localgov_page.localgov_paragraph_content in **localgov_page** to allow this paragraph type.

Then within **localgov_microsites_group**
- Add a default recent content view with the group relationship 
- Update the paragraph config to limit available views to this view

Then within **localgov_microsites_news**
- Add a recent news view with the group relationship (or extend the default view with another block)
- Update the paragraph config to add this to the available views (not needed if we can update the view config)

Repeat for **localgov_microsites_events**


Questions
1. Use the localgov_block_view or create a new one? 
2. Do we want this paragraph to offer a heading and heading level? 
3. If so, how can we ensure that the heading level of the teasers in the view use the right heading level?

**Comment by msayoung** [comment]
Testing branches
- https://github.com/localgovdrupal/localgov_microsites_group/pull/150 (adds a new view and dependency on new paragraph ) 
- https://github.com/localgovdrupal/localgov_paragraphs/pull/69 ( adds a new paragraph)

**Comment by markconroy** [comment]
Tested both of those branches. I think this is working really well. I'd like to get it merged and then start extending it to add displays for news/events/etc and see how it holds up (but from the outset I don't see any issues with it).

**Comment by msayoung** [comment]
@markconroy can I leave this with you? List of things still to do are above :)

**Comment by markconroy** [comment]
This is ready for testing.

Note: there’s 2 content types I haven’t added this to yet - page and promo - simply because we don’t have any localgov_microsites_page/promo modules yet inside localgov_microsites_group. So, let’s get this complete and merged so it works for news and events, and we can create the modules for the other 2 then and get those merged. I’m trying to keep your code review/testing to a minimum so we can move faster.

**Comment by markconroy** [comment]
@msayoung Will we close this? Looks like all the checkboxes in the issue summary are checked now.

**Comment by msayoung** [comment]
Todo

- Bug: the news and events views aren't showing up in the list
- default microsites recent content view ( and documentation for how to update )
- Default non-microsite view for the basic paragraph ( so no dependency on microsites )

**Comment by stephen-cox** [comment]
I've created a bug for the microsite views listed in the LGD paragraphs module: https://github.com/localgovdrupal/localgov_paragraphs/issues/80

**Comment by msayoung** [comment]
@stephen-cox - would you have a go at updating the field config for one of our microsite sub-modules (news?) on install

**Comment by msayoung** [comment]
@stephen-cox 

The remaining work on this issue was to select our views in the localgov_embed_views paragraph on install of events / news etc. 

I've worked out how to do it basically, though they are unsetting eachother. Could you point me to where I'm going wrong? 

https://github.com/localgovdrupal/localgov_microsites_group/pull/254

**Comment by stephen-cox** [comment]
@msayoung You were just about there. Just needed to load the preselect_views setting, add the new view and then save them, rather than replace the preselect_views setting.

**Comment by msayoung** [comment]
done, closing
