### ISSUE TITLE
Link paragraph: optionally display as a button style

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_paragraphs#92]
Add an option on the Link paragraph to display as a link (underlined with an arrow - as present) or a button style (background colour).

On the link paragraph type (in localgov_paragraphs) add a select field named Style, with the options link|Link (default) and button|Button. 
The field description should read "Choose the style of the link". 

In the paragraph--localgov-link.html.twig  file, use the value of the field to add a class "link--button-style" to the outer div when the button option is selected. 

In the link.css file add the css to style the link as a button. (see button styling in form-items.css )

**Comment by msayoung** [comment]
Assigning to me, but Sonia is looking at this.

**Comment by finnlewis** [comment]
@msayoung the tests are failing on the release pull request. We think it needs options as a dependency in the .info.yml

**Comment by msayoung** [comment]
This was released. closing
