### ISSUE TITLE
Subsites banner image needs 'alt' tag

### ISSUE THREAD

**Issue by cjstevens78** [localgovdrupal/localgov_paragraphs#94]
This came out of an accessibility audit on the Croydon site - its seems that the image used in the banner for subsites doesnt have an 'alt' tag.
<img width="897" alt="Screenshot 2021-03-29 at 12 43 56" src="https://user-images.githubusercontent.com/11304107/112992060-bd5f6b80-915f-11eb-986a-c7665ebe5ad8.png">

**Comment by keelanfh** [comment]
Not sure if this is just a specific issue with this one image, or if there's something in the process for inserting the image that could be improved? @msayoung

**Comment by markconroy** [comment]
All images now have alt field as mandatory, so I'm going to close this one.
